CHANGELOG.md
lib/content_block_tools/content_block_reference.rb
lib/content_block_tools/version.rb
spec/content_block_tools/content_block_reference_spec.rb

In https://github.com/alphagov/publishing-api/pull/2989 we removed the call to `uniq` content references, so we were able to count the number of instances in a page. This replicates this functionality in the gem, so we can move towards using this functionality in Publishing API

Don't `uniq` content references

---

CHANGELOG.md
content_block_tools.gemspec
lib/content_block_tools/version.rb

We won’t be able to install the gem in any repo that doesn’t use this exact version of ActionView (and therefore Rails). Loosening the dependency will help and we can rely on Dependabot to keep the latest version in sync

Loosen Actionview dependency

---

CHANGELOG.md
lib/content_block_tools/content_block.rb
lib/content_block_tools/version.rb
spec/content_block_tools/content_block_spec.rb

This ensures the content block’s details hash is always in the format we expect, which is useful for rendering. We do this by casting the content block to a hash, fetching the `details` key and calling `symbolize_keys` on the resulting hash.

Symbolize keys in content block

---

CHANGELOG.md
content_block_tools.gemspec
lib/content_block_tools/version.rb

We probably don’t need to be so prescriptive. If an app is running any Rails version `>= 6`, we should be OK to support it.

Loosen Actionview dependency further

---

.github/workflows/autorelease.yml
.github/workflows/ci.yml

We’ve recently renamed the repo to be more in line with naming conventions, but not the gem (as this would open up a bit of a can of worms, as there’s no real support in Rubygems for renaming). As a result, we need to specify the gem name in the Github actions, as they default to using the repo name, and both the release and autorelease jobs are failing at the mo

Specify gem name

---

CHANGELOG.md
lib/content_block_tools.rb
lib/content_block_tools/content_block.rb
lib/content_block_tools/content_block_reference.rb
lib/content_block_tools/presenters/base_presenter.rb
lib/content_block_tools/presenters/postal_address_presenter.rb
lib/content_block_tools/version.rb
spec/content_block_tools/content_block_reference_spec.rb
spec/content_block_tools/content_block_spec.rb
spec/content_block_tools/presenters/base_presenter_spec.rb
spec/content_block_tools/presenters/email_address_presenter_spec.rb
spec/content_block_tools/presenters/postal_address_presenter_spec.rb

https://trello.com/c/UWUx0rCF/865-allow-individual-fields-to-be-embedded-with-embed-code 
We want to enable users to pass field names via a Content Blocks embed code, like this:
`{{embed:content_block_email_address:2593f06c-b7c8-4173-9a47-09d9bdd767ef/field_name/another_field}}`
The field names currently can only be keys within a block's `details` json blob.
This PR introduces:
1. requiring the `embed_code` to be passed to a ContentBlock when presenting it, because we now need to know the content of the code to determine whether a field is required.
2. changing the regex match used to find an embed code to include an optional substring containing field names.
I'm using the test type of postal address so we can see it working IRL.
1. The breaking changes are fixed in Publishing API here to …

content modelling/865 fields in embed codes

---

CHANGELOG.md
lib/content_block_tools/presenters/base_presenter.rb
lib/content_block_tools/version.rb
spec/content_block_tools/presenters/base_presenter_spec.rb
spec/content_block_tools/presenters/email_address_presenter_spec.rb
spec/content_block_tools/presenters/postal_address_presenter_spec.rb

- **pass entire embed code to html of block**
- **bump version**
This will allow the logic in the `generate_preview` service in Content Block Manager to grab the embed code from the HTML preview and pass it back to Tools to work out what should be rendered.
----

content modelling/881 add embed code data

---

CHANGELOG.md
lib/content_block_tools.rb
lib/content_block_tools/content_block.rb
lib/content_block_tools/content_block_reference.rb
lib/content_block_tools/presenters/pension_presenter.rb
lib/content_block_tools/version.rb
spec/content_block_tools/presenters/pension_presenter_spec.rb

https://trello.com/c/4Nvssgpk/880-enable-embed-codes-for-pension
- **add a basic presenter for pensions**
- **enable pension as supported block type**

content modelling/880 add pension presenter

---

.github/workflows/ci.yml

This adds a single dummy test that only runs if the test matrices have all passed. This matches the pattern defined in https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html#ci-workflow-for-ruby-gems

Add a test step

---

CHANGELOG.md
lib/content_block_tools/presenters/base_presenter.rb
lib/content_block_tools/version.rb
spec/content_block_tools/presenters/base_presenter_spec.rb

I noticed when working on nested fields, that for previewing functionalities in Content Block Manager and Whitehall the nested fields weren't working, though they were working in Publishing API when generating the content for the frontend - for some reason on the Whitehall side any nested fields in the `details` are returned with the keys as strings. This prevents that causing a problem hopefully.
---

symbolise keys in block details

---

CHANGELOG.md
lib/content_block_tools/content_block.rb
lib/content_block_tools/content_block_reference.rb
lib/content_block_tools/version.rb
spec/content_block_tools/content_block_reference_spec.rb

Trello card: https://trello.com/c/fdJtXlmL/553-tech-spike-investigate-friendly-names-for-content-blocks-embed-codes
This adds support for Content ID aliases as well as UUIDs in embed codes, as well as adding a helper to define what type of content id was provided.

(553) Support content aliases in embed codes

---

CHANGELOG.md
content_block_tools.gemspec
lib/content_block_tools.rb
lib/content_block_tools/content_block.rb
lib/content_block_tools/content_block_reference.rb
lib/content_block_tools/presenters/base_presenter.rb
lib/content_block_tools/presenters/contact_presenter.rb
lib/content_block_tools/presenters/email_address_presenter.rb
lib/content_block_tools/presenters/field_presenters/base_presenter.rb
lib/content_block_tools/presenters/field_presenters/contact/email_address_presenter.rb
spec/content_block_tools/content_block_spec.rb
spec/content_block_tools/presenters/base_presenter_spec.rb
spec/content_block_tools/presenters/contact_presenter_spec.rb
spec/content_block_tools/presenters/email_address_presenter_spec.rb
spec/content_block_tools/presenters/field_presenters/contact/email_address_presenter_spec.rb
spec/content_block_tools/presenters/pension_presenter_spec.rb
spec/content_block_tools/presenters/postal_address_presenter_spec.rb
spec/spec_helper.rb

This creates a presenter for contact blocks - if no field is provided, we show all the values (in a similar way to how Whitehall present contacts), otherwise we present a field. I've also added the concept of a field presenter, which allows us to present email addresses as linked.
There's also some improvements to testing, so we don't get caught out by whitespace in resulting HTML

(CM-51) Create a presenter for contact blocks

---

CHANGELOG.md
lib/content_block_tools/version.rb

- Update dependencies
- Create a presenter for Contact Blocks ([30](https://github.com/alphagov/govuk_content_block_tools/pull/30))

Version 0.5.1

---

CHANGELOG.md
lib/content_block_tools/content_block.rb
lib/content_block_tools/version.rb
spec/content_block_tools/content_block_spec.rb

When blocks are fetched from the database in Whitehall / Content Block Manager and passed to the initializer, the details have stringified keys, which means we get an error when fetching embedded details. Using `symbolize_keys` should get round it ordinarily, but because contact items are multiple levels deep, not all of the keys get symbolised. Using `deep_symbolize_keys` ensure all the keys are converted to symbols.

(CM-51) Use `deep_symbolize_keys` when initializing a block's details

---

CHANGELOG.md
lib/content_block_tools/presenters/block_presenters/contact/telephone_presenter.rb
lib/content_block_tools/version.rb
spec/content_block_tools/presenters/block_presenters/contact/telephone_presenter_spec.rb
spec/content_block_tools/presenters/contact_presenter_spec.rb

- **handle uk call charges for a telephone**
- **remove link from telephone numbers**
- **Update changelog.md**

CM-185: Updates to Telephone

---

CHANGELOG.md
lib/content_block_tools/presenters/base_presenter.rb
lib/content_block_tools/presenters/block_presenters/base_presenter.rb
lib/content_block_tools/presenters/block_presenters/contact/telephone_presenter.rb
lib/content_block_tools/presenters/field_presenters/base_presenter.rb
lib/content_block_tools/version.rb
spec/content_block_tools/presenters/block_presenters/contact/telephone_presenter_spec.rb
spec/content_block_tools/presenters/contact_presenter_spec.rb

At the moment, when attempting to render a telephone number in isolation, the presenter renders a `div` inside a `span`, which is not valid HTML. This results in the HTML wrapped inside the enclosing `span` to be escaped and rendered as text. This is because when field names are provided, we automatically assume the content will be wrapped in a `span`
To get around this, we add `BASE_TAG_TYPE`s to the base Field and Block presenters. If `field_names` are present for an embed code, we fetch the `BASE_TAG_TYPE` from the presenter and use that.
In most cases, this will be a `span`, but we override this when rendering a telephone.
As part of this, I've also fixed the rendering of individual fields within a nested telephone number.

Fix rendering telephone numbers and rendering individual nested fields

---

CHANGELOG.md
lib/content_block_tools/presenters/block_presenters/contact/telephone_presenter.rb
lib/content_block_tools/version.rb
spec/content_block_tools/presenters/block_presenters/contact/telephone_presenter_spec.rb

- **fix UK Call Charges presentation**
Was previously showing `false` if it was set to false
- **Update CHANGELOG.md**
Before
After
---

CM-185: UK Call Charges fix

---

CHANGELOG.md
lib/content_block_tools/presenters/base_presenter.rb
lib/content_block_tools/presenters/block_presenters/base_presenter.rb
lib/content_block_tools/presenters/block_presenters/contact/block_level_contact_item.rb
lib/content_block_tools/presenters/block_presenters/contact/contact_form_presenter.rb
lib/content_block_tools/presenters/block_presenters/contact/email_address_presenter.rb
lib/content_block_tools/presenters/block_presenters/contact/telephone_presenter.rb
lib/content_block_tools/presenters/contact_presenter.rb
lib/content_block_tools/presenters/field_presenters/base_presenter.rb
lib/content_block_tools/version.rb
spec/content_block_tools/presenters/base_presenter_spec.rb
spec/content_block_tools/presenters/block_presenters/contact/contact_form_presenter_spec.rb
spec/content_block_tools/presenters/block_presenters/contact/email_address_presenter_spec.rb
spec/content_block_tools/presenters/block_presenters/contact/telephone_presenter_spec.rb
spec/content_block_tools/presenters/contact_presenter_spec.rb

This adds a `contact` class wrapper to block level items in contacts, which (in combination with https://github.com/alphagov/govuk_publishing_components/pull/4906) fixes the rendering of the telephone blocks

(CM-221) Fix rendering of telephone blocks

---

CHANGELOG.md
content_block_tools.gemspec
lib/content_block_tools.rb
lib/content_block_tools/helpers/govspeak.rb
lib/content_block_tools/presenters/base_presenter.rb
lib/content_block_tools/presenters/block_presenters/base_presenter.rb
lib/content_block_tools/presenters/block_presenters/contact/address_presenter.rb
lib/content_block_tools/presenters/block_presenters/contact/block_level_contact_item.rb
lib/content_block_tools/presenters/block_presenters/contact/telephone_presenter.rb
lib/content_block_tools/presenters/contact_presenter.rb
lib/content_block_tools/version.rb
spec/content_block_tools/helpers/govspeak_spec.rb
spec/content_block_tools/presenters/base_presenter_spec.rb
spec/content_block_tools/presenters/block_presenters/contact/address_presenter_spec.rb
spec/content_block_tools/presenters/block_presenters/contact/contact_form_presenter_spec.rb
spec/content_block_tools/presenters/block_presenters/contact/email_address_presenter_spec.rb
spec/content_block_tools/presenters/block_presenters/contact/telephone_presenter_spec.rb

This updates the individual contact mode blocks to consistently show the parent block's title, as well as showing the telephone mode's title and description (rendered as Govspeak) within the telephone block.
I'm still not 100% happy with this approach, but this is consistent enough for us to get in front of users.

(CM-231) Make title rendering consistent

---

CHANGELOG.md
lib/content_block_tools/content_block_reference.rb
lib/content_block_tools/version.rb
spec/content_block_tools/content_block_reference_spec.rb

Kramdown (the markdown parses that Govspeak is based on) replaces double/triple dashes with en/em dashes. This can cause a problem if an embed code contains double or triple dashes (for example when there is a name collision for an identifier.
It seems the easiest way to combat this is scan the document for special dashes, then replace them with double or triple dashes when initializing the references. This should ensure the codes get found correctly.

(CM-240) Replace special dashes with double/triple dashes

---

CHANGELOG.md
lib/content_block_tools/content_block_reference.rb
lib/content_block_tools/version.rb

At the moment, we’re getting a warning in the logs which is quite noisy:
```bash
/usr/local/bundle/ruby/3.3.0/gems/content_block_tools-0.12.1/lib/content_block_tools/content_block_reference.rb: warning: character class has '-' without escape: /[a-z0-9-–—]+/
/usr/local/bundle/ruby/3.3.0/gems/content_block_tools-0.12.1/lib/content_block_tools/content_block_reference.rb:39: warning: character class has '-' without escape
```
Before we added the en and em dashes, we weren’t getting the warning as the dash was the last character in the sequence. Adding the escape character ensures the regex still works, but gets rid of the noise in the logs.

Add escape character

---

CHANGELOG.md
app/assets/stylesheets/content_block_tools.scss
lib/content_block_tools/version.rb

This wasn’t imported, so applications where govuk-frontend wasn’t fully included choked.

Import govuk links

---

CHANGELOG.md
app/components/content_block_tools/contacts/address_component.html.erb
app/components/content_block_tools/contacts/telephone_component.html.erb
lib/content_block_tools/version.rb

[Jira Ticket](https://gov-uk.atlassian.net/browse/CM-515)
Tweaks two visual issues in some of the content blocks:
1. Removes the trailing `,` (comma) on each line of an address.
2. Removes the gap between the numbers and the opening hours in a telephone number contact block.

(CM-515) Tweak styling content blocks
